// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// ** This file is automatically generated by gapic-generator-typescript. **
// ** https://github.com/googleapis/gapic-generator-typescript **
// ** All changes to this file may be overwritten. **

/* global window */
import * as gax from 'google-gax';
import {Callback, CallOptions, Descriptors, ClientOptions} from 'google-gax';

import * as protos from '../../protos/protos';
import jsonProtos = require('../../protos/protos.json');
/**
 * Client JSON configuration object, loaded from
 * `src/v2/actions_testing_client_config.json`.
 * This file defines retry strategy and timeouts for all API methods in this library.
 */
import * as gapicConfig from './actions_testing_client_config.json';

const version = require('../../../package.json').version;

/**
 *  Actions Testing API which allows developers to run automated tests.
 * @class
 * @memberof v2
 */
export class ActionsTestingClient {
  private _terminated = false;
  private _opts: ClientOptions;
  private _gaxModule: typeof gax | typeof gax.fallback;
  private _gaxGrpc: gax.GrpcClient | gax.fallback.GrpcClient;
  private _protos: {};
  private _defaults: {[method: string]: gax.CallSettings};
  auth: gax.GoogleAuth;
  descriptors: Descriptors = {
    page: {},
    stream: {},
    longrunning: {},
    batching: {},
  };
  innerApiCalls: {[name: string]: Function};
  pathTemplates: {[name: string]: gax.PathTemplate};
  actionsTestingStub?: Promise<{[name: string]: Function}>;

  /**
   * Construct an instance of ActionsTestingClient.
   *
   * @param {object} [options] - The configuration object.
   * The options accepted by the constructor are described in detail
   * in [this document](https://github.com/googleapis/gax-nodejs/blob/master/client-libraries.md#creating-the-client-instance).
   * The common options are:
   * @param {object} [options.credentials] - Credentials object.
   * @param {string} [options.credentials.client_email]
   * @param {string} [options.credentials.private_key]
   * @param {string} [options.email] - Account email address. Required when
   *     using a .pem or .p12 keyFilename.
   * @param {string} [options.keyFilename] - Full path to the a .json, .pem, or
   *     .p12 key downloaded from the Google Developers Console. If you provide
   *     a path to a JSON file, the projectId option below is not necessary.
   *     NOTE: .pem and .p12 require you to specify options.email as well.
   * @param {number} [options.port] - The port on which to connect to
   *     the remote host.
   * @param {string} [options.projectId] - The project ID from the Google
   *     Developer's Console, e.g. 'grape-spaceship-123'. We will also check
   *     the environment variable GCLOUD_PROJECT for your project ID. If your
   *     app is running in an environment which supports
   *     {@link https://developers.google.com/identity/protocols/application-default-credentials Application Default Credentials},
   *     your project ID will be detected automatically.
   * @param {string} [options.apiEndpoint] - The domain name of the
   *     API remote host.
   * @param {gax.ClientConfig} [options.clientConfig] - Client configuration override.
   *     Follows the structure of {@link gapicConfig}.
   * @param {boolean} [options.fallback] - Use HTTP fallback mode.
   *     In fallback mode, a special browser-compatible transport implementation is used
   *     instead of gRPC transport. In browser context (if the `window` object is defined)
   *     the fallback mode is enabled automatically; set `options.fallback` to `false`
   *     if you need to override this behavior.
   */
  constructor(opts?: ClientOptions) {
    // Ensure that options include all the required fields.
    const staticMembers = this.constructor as typeof ActionsTestingClient;
    const servicePath = opts?.servicePath || opts?.apiEndpoint || staticMembers.servicePath;
    const port = opts?.port || staticMembers.port;
    const clientConfig = opts?.clientConfig ?? {};
    const fallback = opts?.fallback ?? (typeof window !== 'undefined' && typeof window?.fetch === 'function');
    opts = Object.assign({servicePath, port, clientConfig, fallback}, opts);

    // If scopes are unset in options and we're connecting to a non-default endpoint, set scopes just in case.
    if (servicePath !== staticMembers.servicePath && !('scopes' in opts)) {
      opts['scopes'] = staticMembers.scopes;
    }

    // Choose either gRPC or proto-over-HTTP implementation of google-gax.
    this._gaxModule = opts.fallback ? gax.fallback : gax;

    // Create a `gaxGrpc` object, with any grpc-specific options sent to the client.
    this._gaxGrpc = new this._gaxModule.GrpcClient(opts);

    // Save options to use in initialize() method.
    this._opts = opts;

    // Save the auth object to the client, for use by other methods.
    this.auth = (this._gaxGrpc.auth as gax.GoogleAuth);

    // Set the default scopes in auth client if needed.
    if (servicePath === staticMembers.servicePath) {
      this.auth.defaultScopes = staticMembers.scopes;
    }

    // Determine the client header string.
    const clientHeader = [
      `gax/${this._gaxModule.version}`,
      `gapic/${version}`,
    ];
    if (typeof process !== 'undefined' && 'versions' in process) {
      clientHeader.push(`gl-node/${process.versions.node}`);
    } else {
      clientHeader.push(`gl-web/${this._gaxModule.version}`);
    }
    if (!opts.fallback) {
      clientHeader.push(`grpc/${this._gaxGrpc.grpcVersion}`);
    }
    if (opts.libName && opts.libVersion) {
      clientHeader.push(`${opts.libName}/${opts.libVersion}`);
    }
    // Load the applicable protos.
    this._protos = this._gaxGrpc.loadProtoJSON(jsonProtos);

    // This API contains "path templates"; forward-slash-separated
    // identifiers to uniquely identify resources within the API.
    // Create useful helper objects for these.
    this.pathTemplates = {
      draftPathTemplate: new this._gaxModule.PathTemplate(
        'projects/{project}/draft'
      ),
      previewPathTemplate: new this._gaxModule.PathTemplate(
        'projects/{project}/previews/{preview}'
      ),
      releaseChannelPathTemplate: new this._gaxModule.PathTemplate(
        'projects/{project}/releaseChannels/{release_channel}'
      ),
      sampleProjectPathTemplate: new this._gaxModule.PathTemplate(
        'sampleProjects/{sample_project}'
      ),
      versionPathTemplate: new this._gaxModule.PathTemplate(
        'projects/{project}/versions/{version}'
      ),
    };

    // Put together the default options sent with requests.
    this._defaults = this._gaxGrpc.constructSettings(
        'google.actions.sdk.v2.ActionsTesting', gapicConfig as gax.ClientConfig,
        opts.clientConfig || {}, {'x-goog-api-client': clientHeader.join(' ')});

    // Set up a dictionary of "inner API calls"; the core implementation
    // of calling the API is handled in `google-gax`, with this code
    // merely providing the destination and request information.
    this.innerApiCalls = {};
  }

  /**
   * Initialize the client.
   * Performs asynchronous operations (such as authentication) and prepares the client.
   * This function will be called automatically when any class method is called for the
   * first time, but if you need to initialize it before calling an actual method,
   * feel free to call initialize() directly.
   *
   * You can await on this method if you want to make sure the client is initialized.
   *
   * @returns {Promise} A promise that resolves to an authenticated service stub.
   */
  initialize() {
    // If the client stub promise is already initialized, return immediately.
    if (this.actionsTestingStub) {
      return this.actionsTestingStub;
    }

    // Put together the "service stub" for
    // google.actions.sdk.v2.ActionsTesting.
    this.actionsTestingStub = this._gaxGrpc.createStub(
        this._opts.fallback ?
          (this._protos as protobuf.Root).lookupService('google.actions.sdk.v2.ActionsTesting') :
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          (this._protos as any).google.actions.sdk.v2.ActionsTesting,
        this._opts) as Promise<{[method: string]: Function}>;

    // Iterate over each of the methods that the service provides
    // and create an API call method for each.
    const actionsTestingStubMethods =
        ['sendInteraction', 'matchIntents', 'setWebAndAppActivityControl'];
    for (const methodName of actionsTestingStubMethods) {
      const callPromise = this.actionsTestingStub.then(
        stub => (...args: Array<{}>) => {
          if (this._terminated) {
            return Promise.reject('The client has already been closed.');
          }
          const func = stub[methodName];
          return func.apply(stub, args);
        },
        (err: Error|null|undefined) => () => {
          throw err;
        });

      const descriptor =
        undefined;
      const apiCall = this._gaxModule.createApiCall(
        callPromise,
        this._defaults[methodName],
        descriptor
      );

      this.innerApiCalls[methodName] = apiCall;
    }

    return this.actionsTestingStub;
  }

  /**
   * The DNS address for this API service.
   * @returns {string} The DNS address for this service.
   */
  static get servicePath() {
    return 'actions.googleapis.com';
  }

  /**
   * The DNS address for this API service - same as servicePath(),
   * exists for compatibility reasons.
   * @returns {string} The DNS address for this service.
   */
  static get apiEndpoint() {
    return 'actions.googleapis.com';
  }

  /**
   * The port for this API service.
   * @returns {number} The default port for this service.
   */
  static get port() {
    return 443;
  }

  /**
   * The scopes needed to make gRPC calls for every method defined
   * in this service.
   * @returns {string[]} List of default scopes.
   */
  static get scopes() {
    return [];
  }

  getProjectId(): Promise<string>;
  getProjectId(callback: Callback<string, undefined, undefined>): void;
  /**
   * Return the project ID used by this class.
   * @returns {Promise} A promise that resolves to string containing the project ID.
   */
  getProjectId(callback?: Callback<string, undefined, undefined>):
      Promise<string>|void {
    if (callback) {
      this.auth.getProjectId(callback);
      return;
    }
    return this.auth.getProjectId();
  }

  // -------------------
  // -- Service calls --
  // -------------------
  sendInteraction(
      request: protos.google.actions.sdk.v2.ISendInteractionRequest,
      options?: CallOptions):
      Promise<[
        protos.google.actions.sdk.v2.ISendInteractionResponse,
        protos.google.actions.sdk.v2.ISendInteractionRequest|undefined, {}|undefined
      ]>;
  sendInteraction(
      request: protos.google.actions.sdk.v2.ISendInteractionRequest,
      options: CallOptions,
      callback: Callback<
          protos.google.actions.sdk.v2.ISendInteractionResponse,
          protos.google.actions.sdk.v2.ISendInteractionRequest|null|undefined,
          {}|null|undefined>): void;
  sendInteraction(
      request: protos.google.actions.sdk.v2.ISendInteractionRequest,
      callback: Callback<
          protos.google.actions.sdk.v2.ISendInteractionResponse,
          protos.google.actions.sdk.v2.ISendInteractionRequest|null|undefined,
          {}|null|undefined>): void;
/**
 * Plays one round of the conversation.
 *
 * @param {Object} request
 *   The request object that will be sent.
 * @param {string} request.project
 *   Required. The project being tested, indicated by the Project ID.
 *   Format: projects/{project}
 * @param {google.actions.sdk.v2.UserInput} request.input
 *   Required. Input provided by the user.
 * @param {google.actions.sdk.v2.DeviceProperties} request.deviceProperties
 *   Required. Properties of the device used for interacting with the Action.
 * @param {string} request.conversationToken
 *   Opaque token that must be passed as received from SendInteractionResponse
 *   on the previous interaction. This can be left unset in order to start a new
 *   conversation, either as the first interaction of a testing session or to
 *   abandon a previous conversation and start a new one.
 * @param {object} [options]
 *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
 * @returns {Promise} - The promise which resolves to an array.
 *   The first element of the array is an object representing [SendInteractionResponse]{@link google.actions.sdk.v2.SendInteractionResponse}.
 *   Please see the
 *   [documentation](https://github.com/googleapis/gax-nodejs/blob/master/client-libraries.md#regular-methods)
 *   for more details and examples.
 * @example
 * const [response] = await client.sendInteraction(request);
 */
  sendInteraction(
      request: protos.google.actions.sdk.v2.ISendInteractionRequest,
      optionsOrCallback?: CallOptions|Callback<
          protos.google.actions.sdk.v2.ISendInteractionResponse,
          protos.google.actions.sdk.v2.ISendInteractionRequest|null|undefined,
          {}|null|undefined>,
      callback?: Callback<
          protos.google.actions.sdk.v2.ISendInteractionResponse,
          protos.google.actions.sdk.v2.ISendInteractionRequest|null|undefined,
          {}|null|undefined>):
      Promise<[
        protos.google.actions.sdk.v2.ISendInteractionResponse,
        protos.google.actions.sdk.v2.ISendInteractionRequest|undefined, {}|undefined
      ]>|void {
    request = request || {};
    let options: CallOptions;
    if (typeof optionsOrCallback === 'function' && callback === undefined) {
      callback = optionsOrCallback;
      options = {};
    }
    else {
      options = optionsOrCallback as CallOptions;
    }
    options = options || {};
    options.otherArgs = options.otherArgs || {};
    options.otherArgs.headers = options.otherArgs.headers || {};
    options.otherArgs.headers[
      'x-goog-request-params'
    ] = gax.routingHeader.fromParams({
      'project': request.project || '',
    });
    this.initialize();
    return this.innerApiCalls.sendInteraction(request, options, callback);
  }
  matchIntents(
      request: protos.google.actions.sdk.v2.IMatchIntentsRequest,
      options?: CallOptions):
      Promise<[
        protos.google.actions.sdk.v2.IMatchIntentsResponse,
        protos.google.actions.sdk.v2.IMatchIntentsRequest|undefined, {}|undefined
      ]>;
  matchIntents(
      request: protos.google.actions.sdk.v2.IMatchIntentsRequest,
      options: CallOptions,
      callback: Callback<
          protos.google.actions.sdk.v2.IMatchIntentsResponse,
          protos.google.actions.sdk.v2.IMatchIntentsRequest|null|undefined,
          {}|null|undefined>): void;
  matchIntents(
      request: protos.google.actions.sdk.v2.IMatchIntentsRequest,
      callback: Callback<
          protos.google.actions.sdk.v2.IMatchIntentsResponse,
          protos.google.actions.sdk.v2.IMatchIntentsRequest|null|undefined,
          {}|null|undefined>): void;
/**
 * Finds the intents that match a given query.
 *
 * @param {Object} request
 *   The request object that will be sent.
 * @param {string} request.project
 *   Required. The project being tested, indicated by the Project ID.
 *   Format: projects/{project}
 * @param {string} request.query
 *   Required. User query as plain text.
 * @param {string} request.locale
 *   Required. Locale to use to evaluate the query, such as "en".
 *   The format should follow BCP 47: https://tools.ietf.org/html/bcp47
 *   See the list of supported languages in
 *   https://developers.google.com/assistant/console/languages-locales
 * @param {object} [options]
 *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
 * @returns {Promise} - The promise which resolves to an array.
 *   The first element of the array is an object representing [MatchIntentsResponse]{@link google.actions.sdk.v2.MatchIntentsResponse}.
 *   Please see the
 *   [documentation](https://github.com/googleapis/gax-nodejs/blob/master/client-libraries.md#regular-methods)
 *   for more details and examples.
 * @example
 * const [response] = await client.matchIntents(request);
 */
  matchIntents(
      request: protos.google.actions.sdk.v2.IMatchIntentsRequest,
      optionsOrCallback?: CallOptions|Callback<
          protos.google.actions.sdk.v2.IMatchIntentsResponse,
          protos.google.actions.sdk.v2.IMatchIntentsRequest|null|undefined,
          {}|null|undefined>,
      callback?: Callback<
          protos.google.actions.sdk.v2.IMatchIntentsResponse,
          protos.google.actions.sdk.v2.IMatchIntentsRequest|null|undefined,
          {}|null|undefined>):
      Promise<[
        protos.google.actions.sdk.v2.IMatchIntentsResponse,
        protos.google.actions.sdk.v2.IMatchIntentsRequest|undefined, {}|undefined
      ]>|void {
    request = request || {};
    let options: CallOptions;
    if (typeof optionsOrCallback === 'function' && callback === undefined) {
      callback = optionsOrCallback;
      options = {};
    }
    else {
      options = optionsOrCallback as CallOptions;
    }
    options = options || {};
    options.otherArgs = options.otherArgs || {};
    options.otherArgs.headers = options.otherArgs.headers || {};
    options.otherArgs.headers[
      'x-goog-request-params'
    ] = gax.routingHeader.fromParams({
      'project': request.project || '',
    });
    this.initialize();
    return this.innerApiCalls.matchIntents(request, options, callback);
  }
  setWebAndAppActivityControl(
      request: protos.google.actions.sdk.v2.ISetWebAndAppActivityControlRequest,
      options?: CallOptions):
      Promise<[
        protos.google.protobuf.IEmpty,
        protos.google.actions.sdk.v2.ISetWebAndAppActivityControlRequest|undefined, {}|undefined
      ]>;
  setWebAndAppActivityControl(
      request: protos.google.actions.sdk.v2.ISetWebAndAppActivityControlRequest,
      options: CallOptions,
      callback: Callback<
          protos.google.protobuf.IEmpty,
          protos.google.actions.sdk.v2.ISetWebAndAppActivityControlRequest|null|undefined,
          {}|null|undefined>): void;
  setWebAndAppActivityControl(
      request: protos.google.actions.sdk.v2.ISetWebAndAppActivityControlRequest,
      callback: Callback<
          protos.google.protobuf.IEmpty,
          protos.google.actions.sdk.v2.ISetWebAndAppActivityControlRequest|null|undefined,
          {}|null|undefined>): void;
/**
 * Sets the Web & App Activity control on a service account.
 *
 * It is necessary to have this setting enabled in order to use call Actions.
 * The setting is originally disabled for service accounts, and it is
 * preserved until set to a different value. This means it only needs to be
 * enabled once per account (and not necessarily once per test), unless it is
 * later disabled.
 *
 * Returns an error if the caller is not a service account. User accounts can
 * change this setting via the Activity Controls page. See
 * https://support.google.com/websearch/answer/54068.
 *
 * @param {Object} request
 *   The request object that will be sent.
 * @param {boolean} request.enabled
 *   Whether the setting should be set to an enabled or disabled state.
 * @param {object} [options]
 *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
 * @returns {Promise} - The promise which resolves to an array.
 *   The first element of the array is an object representing [Empty]{@link google.protobuf.Empty}.
 *   Please see the
 *   [documentation](https://github.com/googleapis/gax-nodejs/blob/master/client-libraries.md#regular-methods)
 *   for more details and examples.
 * @example
 * const [response] = await client.setWebAndAppActivityControl(request);
 */
  setWebAndAppActivityControl(
      request: protos.google.actions.sdk.v2.ISetWebAndAppActivityControlRequest,
      optionsOrCallback?: CallOptions|Callback<
          protos.google.protobuf.IEmpty,
          protos.google.actions.sdk.v2.ISetWebAndAppActivityControlRequest|null|undefined,
          {}|null|undefined>,
      callback?: Callback<
          protos.google.protobuf.IEmpty,
          protos.google.actions.sdk.v2.ISetWebAndAppActivityControlRequest|null|undefined,
          {}|null|undefined>):
      Promise<[
        protos.google.protobuf.IEmpty,
        protos.google.actions.sdk.v2.ISetWebAndAppActivityControlRequest|undefined, {}|undefined
      ]>|void {
    request = request || {};
    let options: CallOptions;
    if (typeof optionsOrCallback === 'function' && callback === undefined) {
      callback = optionsOrCallback;
      options = {};
    }
    else {
      options = optionsOrCallback as CallOptions;
    }
    options = options || {};
    this.initialize();
    return this.innerApiCalls.setWebAndAppActivityControl(request, options, callback);
  }

  // --------------------
  // -- Path templates --
  // --------------------

  /**
   * Return a fully-qualified draft resource name string.
   *
   * @param {string} project
   * @returns {string} Resource name string.
   */
  draftPath(project:string) {
    return this.pathTemplates.draftPathTemplate.render({
      project: project,
    });
  }

  /**
   * Parse the project from Draft resource.
   *
   * @param {string} draftName
   *   A fully-qualified path representing Draft resource.
   * @returns {string} A string representing the project.
   */
  matchProjectFromDraftName(draftName: string) {
    return this.pathTemplates.draftPathTemplate.match(draftName).project;
  }

  /**
   * Return a fully-qualified preview resource name string.
   *
   * @param {string} project
   * @param {string} preview
   * @returns {string} Resource name string.
   */
  previewPath(project:string,preview:string) {
    return this.pathTemplates.previewPathTemplate.render({
      project: project,
      preview: preview,
    });
  }

  /**
   * Parse the project from Preview resource.
   *
   * @param {string} previewName
   *   A fully-qualified path representing Preview resource.
   * @returns {string} A string representing the project.
   */
  matchProjectFromPreviewName(previewName: string) {
    return this.pathTemplates.previewPathTemplate.match(previewName).project;
  }

  /**
   * Parse the preview from Preview resource.
   *
   * @param {string} previewName
   *   A fully-qualified path representing Preview resource.
   * @returns {string} A string representing the preview.
   */
  matchPreviewFromPreviewName(previewName: string) {
    return this.pathTemplates.previewPathTemplate.match(previewName).preview;
  }

  /**
   * Return a fully-qualified releaseChannel resource name string.
   *
   * @param {string} project
   * @param {string} release_channel
   * @returns {string} Resource name string.
   */
  releaseChannelPath(project:string,releaseChannel:string) {
    return this.pathTemplates.releaseChannelPathTemplate.render({
      project: project,
      release_channel: releaseChannel,
    });
  }

  /**
   * Parse the project from ReleaseChannel resource.
   *
   * @param {string} releaseChannelName
   *   A fully-qualified path representing ReleaseChannel resource.
   * @returns {string} A string representing the project.
   */
  matchProjectFromReleaseChannelName(releaseChannelName: string) {
    return this.pathTemplates.releaseChannelPathTemplate.match(releaseChannelName).project;
  }

  /**
   * Parse the release_channel from ReleaseChannel resource.
   *
   * @param {string} releaseChannelName
   *   A fully-qualified path representing ReleaseChannel resource.
   * @returns {string} A string representing the release_channel.
   */
  matchReleaseChannelFromReleaseChannelName(releaseChannelName: string) {
    return this.pathTemplates.releaseChannelPathTemplate.match(releaseChannelName).release_channel;
  }

  /**
   * Return a fully-qualified sampleProject resource name string.
   *
   * @param {string} sample_project
   * @returns {string} Resource name string.
   */
  sampleProjectPath(sampleProject:string) {
    return this.pathTemplates.sampleProjectPathTemplate.render({
      sample_project: sampleProject,
    });
  }

  /**
   * Parse the sample_project from SampleProject resource.
   *
   * @param {string} sampleProjectName
   *   A fully-qualified path representing SampleProject resource.
   * @returns {string} A string representing the sample_project.
   */
  matchSampleProjectFromSampleProjectName(sampleProjectName: string) {
    return this.pathTemplates.sampleProjectPathTemplate.match(sampleProjectName).sample_project;
  }

  /**
   * Return a fully-qualified version resource name string.
   *
   * @param {string} project
   * @param {string} version
   * @returns {string} Resource name string.
   */
  versionPath(project:string,version:string) {
    return this.pathTemplates.versionPathTemplate.render({
      project: project,
      version: version,
    });
  }

  /**
   * Parse the project from Version resource.
   *
   * @param {string} versionName
   *   A fully-qualified path representing Version resource.
   * @returns {string} A string representing the project.
   */
  matchProjectFromVersionName(versionName: string) {
    return this.pathTemplates.versionPathTemplate.match(versionName).project;
  }

  /**
   * Parse the version from Version resource.
   *
   * @param {string} versionName
   *   A fully-qualified path representing Version resource.
   * @returns {string} A string representing the version.
   */
  matchVersionFromVersionName(versionName: string) {
    return this.pathTemplates.versionPathTemplate.match(versionName).version;
  }

  /**
   * Terminate the gRPC channel and close the client.
   *
   * The client will no longer be usable and all future behavior is undefined.
   * @returns {Promise} A promise that resolves when the client is closed.
   */
  close(): Promise<void> {
    this.initialize();
    if (!this._terminated) {
      return this.actionsTestingStub!.then(stub => {
        this._terminated = true;
        stub.close();
      });
    }
    return Promise.resolve();
  }
}
